### ISSUE TITLE
Make configuration less verbose

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-htop#6]
```yaml
htop_htoprc_destinations:
  skell:
    dest: /etc/skel/.config/htop
  current:
    dest: "{{ ansible_env.HOME }}/.config/htop"
  mtersmitten:
    dest: /home/mtersmitten/.config/htop
    owner: mtersmitten
    group: mtersmitten
```

There should be no need to specify `group` when it's the same as `owner`.
